apiVersion: v2
name: status-list-server
description: Helm chart for deploying status list server on AWS EKS
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgres
    version: 0.8.2
    repository: oci://registry-1.docker.io/cloudpirates
  - name: redis-ha
    version: 4.35.0
    repository: https://dandydeveloper.github.io/charts
  - name: postgresql
    version: "15.3.0"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: postgresql.enabled
  - name: redis
    version: "19.1.1"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: redis.enabled