apiVersion: v2
name: status-list-server
description: Helm chart for deploying status list server on AWS EKS
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: 16.7.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 21.2.13
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled