{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecret.spec.secretStoreRef.name }}
  labels:
    {{- include "status-list-server-chart.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.aws.region }}
{{- end }}
