{{- if .Values.statuslist.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "status-list-server-chart.fullname" . }}-service
  labels:
    {{- include "status-list-server-chart.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.statuslist.service.type }}
  ports:
  - name: http
    port: {{ .Values.statuslist.service.port }}
    targetPort: {{ .Values.statuslist.service.targetPort }}
    protocol: TCP
    {{- if and (eq .Values.statuslist.service.type "NodePort") .Values.statuslist.service.nodePort }}
    nodePort: {{ .Values.statuslist.service.nodePort }}
    {{- end }}
  selector:
    {{- include "status-list-server-chart.selectorLabels" . | nindent 4 }}
{{- end }}
