apiVersion: v2
name: status-list-server
description: Helm chart for deploying status list server on AWS EKS
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "14.2.3"
    repository: https://charts.bitnami.com/bitnami
    condition: postgres.enabled
  - name: redis
    version: "18.14.0"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled